name: Is Build Successfully

on: push

jobs:
  # https://github.com/marketplace/actions/github-action-for-yarn
  build_and_test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      # 환경변수에 내용을 추가해야 할 때 이 stage에도 추가해주세요
      - name: Add DotEnv
        env:
          PORT: ${{ secrets.PORT }}
          API_URL: ${{ secrets.API_URL }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          echo PORT=$PORT >> .env
          echo API_URL=$API_URL >> .env
          echo BASE_URL=$BASE_URL >> .env

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn prod` command
